In [3]:
import numpy as np


In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [18]:
b = np.array([[1.2,3.5,8.6],[5.2,4.3,9.8]])
print(b)

[[1.2 3.5 8.6]
 [5.2 4.3 9.8]]


In [20]:
#Get Dimention
a.ndim
b.ndim

2

In [22]:
#Get Shape
b.shape

(3,)

In [23]:
#Get type
a.dtype

dtype('int32')

In [24]:
#Get Size
a.itemsize

4

In [26]:
#total size
a.size*a.itemsize
#or
a.nbytes

12

In [15]:
a = np.array([[1,2,5,4,7,8,5],[9,6,3,5,8,17,4]])
print(a)

[[ 1  2  5  4  7  8  5]
 [ 9  6  3  5  8 17  4]]


In [28]:
a.shape

(2, 7)

In [30]:
#get a specific element [row, column]
#python starts  from 0, so if we wanna get 17 we should set row as index 1 and column as 5
a [1,5]

17

In [31]:
#we can also get by the negetives
a[1,-2]

17

In [32]:
# get a specific row
a[0, :]

array([1, 2, 5, 4, 7, 8, 5])

In [34]:
#get a specific column
a[ :, 0]

array([1, 9])

In [35]:
# getting a little moew fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 8])

In [36]:
a[1,5] = 20
print(a)

[[ 1  2  5  4  7  8  5]
 [ 9  6  3  5  8 20  4]]


In [ ]:
# 3d example

In [16]:
c = np.array([[[1,2],[5,6]],[[3,4],[8,9]]])
print(c)

[[[1 2]
  [5 6]]

 [[3 4]
  [8 9]]]


In [40]:
#get specific element(work outside in) below will give us(first set,second row, second idex )
c[0,1,1]

6

In [47]:
#replace
c[:,1,:] = [[9,9],[8,8]]
print(c)

[[[1 2]
  [9 9]]

 [[3 4]
  [8 8]]]


In [5]:
#all 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#all 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [7]:
#all 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [9]:
# any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [17]:
#any other number(full_like) for example if we wanna make arrey like c that we had before
np.full_like(c,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [22]:
#Random decimal number
np.random.rand(4,2,3)

array([[[0.43734342, 0.15201326, 0.27882485],
        [0.9943512 , 0.57311989, 0.92011555]],

       [[0.30421081, 0.99552665, 0.67593514],
        [0.61852895, 0.1848151 , 0.21646071]],

       [[0.29178833, 0.86317535, 0.81050869],
        [0.75152909, 0.57551104, 0.28456504]],

       [[0.3823037 , 0.07352942, 0.08076625],
        [0.01910121, 0.37694117, 0.52116422]]])

In [25]:
#random integer values
np.random.randint(-4,8, size=(3,3))

array([[ 6,  0,  2],
       [-1,  3,  6],
       [ 0,  1,  1]])

In [27]:
#identity natrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
#repeat the array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print (r1)

[1 1 1 2 2 2 3 3 3]


In [31]:
#repeat the array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis =0)
print (r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [32]:
# solution to create this matrix:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

#create the ones matrix
output = np.ones((5,5))
print(output)

#create the zeroz and replace the (1,1) cell with 9
z = np.zeros((3,3))
z[1,1] = 9
print(z)

#then put the second mterix in the first one
output[1:4,1:4] = z  #instead of 4 we can also use -1--> output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###### Be careful when copying arrays!!!!


In [35]:
a  = np.array([1,2,3])
b = a.copy()  # we need to make a copy not simply make them equal
b[0] =100

print(a)

[1 2 3]


#### Mathematics

In [36]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [37]:
a + 2

array([3, 4, 5, 6])

In [38]:
a - 2

array([-1,  0,  1,  2])

In [39]:
a * 2

array([2, 4, 6, 8])

In [40]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [41]:
#create another array

b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [42]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [44]:
#take the sin and cos of all values
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

##### Linear Algebra

In [46]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

##### Statistics

In [47]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.max(stats)

6

In [50]:
np.min(stats)

1

In [51]:
#min of the firat row and min of the second row
np.min(stats, axis=1)

array([1, 4])

In [52]:
np.sum(stats)

21

In [53]:
np.sum(stats, axis=0)

array([5, 7, 9])

##### Reorganizing Arryas

In [57]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

# to resize the array we should pass the size that we want
after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [59]:
#vertical stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])
# we can keep passing in if we want moew copies
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [63]:
# horizantal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))


np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

##### Boolean Masking and Advanced Indexing